### ISSUE TITLE
Dynamic ads with configurable products. 

### ISSUE THREAD

**Issue by whoisdaneil** [facebookincubator/facebook-for-magento#48] opened 2018-03-30 15:53 UTC
At first, thank you for this extension!

We have a shop with 29 configurable products, each with more that 100 configurations. 

How can we get the selected „simple product“ exported to Facebook and used in dynamic ads?

**Comment by mengyingdu** [comment] 2018-03-31 02:50
Hi @whoisdaneil ,

Can you explain what is configuration products? I haven't heard it before. Are you using other plugins at the same time?
Do you know about this? @dmitridr 

Thanks.

**Comment by whoisdaneil** [comment] 2018-03-31 06:48
Hi @mengyingdu 
configurable products "Main Product" are products with different "Child Products/Options" and is standard in Magento. In a configurable products are made from many simple products.

Example: A T-Shirt "Main Product" with different sizes und colors "Options". The catalog just shows the "Main Product" but not the "Options" the customer selected. In backend you will have with 5 colors and 5 sizes. 25 different simple products. With own url/EAN/description/price. It frontend and catalog you just have one.

I our shop the customer just chooses one Smartphone "Main Product" We are selling smartphone accessories. He wouldn't switch between and iPhone 5 oder X for example. I think ist would be more effective if the customer gets shown also options he has selected. At the T-Shirt example I'll be a customer which looked at Size M, colors Blue and green, and the Dynamic add is showing me the mail picture "T-Shirt" and thats it. For good UX it hast to show the blue and the green one.

We added some other plugins/extensions for dynamic switching. Description,price and pictures depending on selected "Options" are switching when selected and before adding to cart. Could a dynamic switching url, to simple products url, solve the problem? What does the catalog need to identify the products?

**Comment by dmitridr** [comment] 2018-04-02 21:08
Unfortunately, right now the plugin does not support the import of all simple products inside the configurable product, only the configurable product is imported to FB. This is by design. However there may be a workaround...

I believe that if the Simple products are marked as not individually visible, they will not import, so one solution to try may be to mark them as individually visible, then export the products. These should import to FB. Could you try this approach? 

I tested on our own servers and if the Simple product under the Configurable was marked as visible in 'Catalog', it did import into FB.

**Comment by whoisdaneil** [comment] 2018-04-03 10:29
Hello @dmitridr,
that's a good Idea I will test that with some products.

Best regards, Daniel

**Comment by mpalasis** [comment] 2018-04-06 02:03
alternatively you can look at the code for `getModel('catalog/product')->getCollection()` and when you figure out the login and which one is the one for the task at hand; you can tweak the filter in there. Not too easy, but might be doable... worst case scenario check for parent product and a list of all 29 configurable product Ids in the query, something like: `IN (id1,id2, ... idN)`

**Comment by dmitridr** [comment] 2018-04-11 19:04
@whoisdaneil 

One suggestion to fix your dillema : you should be able to see the location of the product feed file in the [settings of your catalog](www.facebook.com/products/). You can use this product feed file to create a new catalog, and use that catalog for Dynamic Ads, then use the catalog created by this extension to continue using the shop. Hope that helps!

**Comment by dmitridr** [comment] 2018-04-11 19:11
The only way I see that this can be fully fixed (including the shop problem) is if we fully support variable products within the shop. This would mean that simple products appear as selectable dropdown items in the shop. This will, in turn, cause many other issues.

**Closed** 2018-07-04 17:19 UTC
Labels: question
