### ISSUE TITLE
SKU in Title

### ISSUE THREAD

**Issue by dimitraros** [facebookincubator/facebook-for-magento#16] opened 2017-10-16 09:39 UTC
Hi, i have a lot of products with the same title and when I try to tag a product, i can't find the one i want, because in every search, Facebook shows me only 10 results. Therefore, i tried adding the Sku in the title with the following format: Title | Sku 

i added just after line 190 in  FacebookProductFeed.php (buildProductEntry function):
`$sku = $product->getSku();
    $titlenew = $title.' | '.$sku;`

and then changed line 195 to:
`$items[self::ATTR_TITLE] = $this->buildProductAttr(self::ATTR_TITLE, $titlenew);`

I fetched the products and i can see the new format in Facebook Catalog (with the | separator), but the encoding is wrong and the letters are not readable. All my product titles are in Greek and they were all readable in FB before my code changes. What is wrong with my code that changes the encoding?

**Comment by dmitridr** [comment] 2017-10-16 21:58
Hello, 

If you have set up the extension with us a long time ago, it's possible your product feed is set up to auto-detect the correct encoding. My guess is the addition of the | to all products messed that up somehow. The other possibility is that the `$sku` has some different incompatible encoding.

Here is what I would recommend trying:
- Revert code changes, Force resync. Verify that product titles are back to normal and readable. (Sanity Check)
- Put back code changes, try `$title.' '.$sku` same problem? If yes try `$title.$sku` ? In this case, it's likely the problem is not with | but with $sku has some strange encoding, does it? You may be able to use some php function to sanitize it if so. If you know the source encoding of the $sku you can use this function : 
http://php.net/manual/en/function.mb-convert-encoding.php

e.g. $sku = mb_convert_encoding($sku, "UTF-8", "auto");

Hope that helps.

**Comment by dimitraros** [comment] 2017-10-18 09:23
Hi dmitridr

thanks for the reply. I can confirm that both the $title and the $sku variables have no encoding problems ($title.$sku works great but as you can understand i need something that makes more sense), so the problems occurs when i try to insert something in between (eg ' | ' or ' '). I tried to use the mb_convert_encoding function:

`$titlenew = $title.mb_convert_encoding(' | ', 'UTF-8').$sku;` or
`$titlenew = $title.' | '.$sku;
$titlenew = mb_convert_encoding($titlenew, 'UTF-8');` 

but no luck, i still get the non readable characters.

**Comment by dmitridr** [comment] 2017-11-09 20:44
Very strange. Even when using ' ' ? I wonder why that happens. There are a couple more things to try that I can think of:

- If you'd like to rule out the issue of encoding auto-detection on our side, you can try resetting your integration with FB, this will re-create the feed object on our side. 
- You could also try creating a new feed using the Catalog Manager interface on Facebook, then using the feed url for your file to see if it works that way.
- You could try using just '|' ? Maybe the problem is with the spaces.

**Comment by dmitridr** [comment] 2018-07-17 21:47
Closing this, as it has been a while with no resolution or reply. We cannot reproduce this bug, unfortunately.

**Closed by dmitridr** 2018-07-17 21:47 UTC
Labels: question
