### ISSUE TITLE
Catalog is taking product no. in Content ID instead of SKUs

### ISSUE THREAD

**Issue by adnan-esoft** [facebookincubator/facebook-for-magento#78] opened 2018-08-07 08:01 UTC
Hello All,

I am facing this issue from past couple of months. When I tried to run a remarketing campaign it is showing that catalog content id is not matching with pixel's content id. When I check in the product feed and the content id which pixel is fetching both are different. This plugin is taking product id (123) as a content id whereas Facebook pixel is taking SKUs (Config_xyz_1234) as a content id.
To run a remarketing campaign both the content ids (catalog & pixel) should match. Someone please help me to understand **how I can make changes in the plugin so that it will fetch sku as a content id instead of other things?**

**Comment by dmitridr** [comment] 2018-08-10 19:01
Hello,

Thanks for writing in. 
[Here](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Block/ViewContent.php#L22) is the code where we fetch the content id for the event `ViewContent`. Is this the event you are having issues with?

Normally this should return the product ID, but for you is it returning the SKU? 
Here's some things that would help us narrow down the cause:
- Could you send us a link to your site? We can take a look at what's going on.
- Could you tell us the events that have the problem, is it all events?
- Could you tell us the version of the plugin you are using and the version of Magento? You will want to use the most current version of the plugin, [v2.5.0](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.5.0) in case what you are seeing is a bug that we have solved previously.

Thanks!

**Comment by dmitridr** [comment] 2018-12-14 19:09
Closing as we have not received a reply. Hope you resolved your issue.

**Closed by dmitridr** 2018-12-14 19:09 UTC
Labels: bug

**Comment by ueltonVeslei** [comment] 2020-07-04 03:08
> Hello All,
> 
> I am facing this issue from past couple of months. When I tried to run a remarketing campaign it is showing that catalog content id is not matching with pixel's content id. When I check in the product feed and the content id which pixel is fetching both are different. This plugin is taking product id (123) as a content id whereas Facebook pixel is taking SKUs (Config_xyz_1234) as a content id.
> To run a remarketing campaign both the content ids (catalog & pixel) should match. Someone please help me to understand **how I can make changes in the plugin so that it will fetch sku as a content id instead of other things?**

Can u share the solution, please?
I have the same issue.
