### ISSUE TITLE
magento admin page shows blank

### ISSUE THREAD

**Issue by giftipedia** [facebookincubator/facebook-for-magento#11] opened 2017-10-10 06:22 UTC
Hi,

After installing this extension on two of our websites: 
https://www.giftipedia.com and https://www.kitchenempire.in, giftipedia magento admin panel doesn't show anything while we click on facebook ad extension menu. However, Kitchenmpire is alright and successfully integrated. 

both setup are identical. Can someone help me how to troubleshoot?
![facebook ad extension magento admin blank](https://user-images.githubusercontent.com/32664557/31372014-7df48268-adb1-11e7-8811-fb2949861d21.jpg)

**Comment by dmitridr** [comment] 2017-10-10 23:38
Hello, 

That's very strange, but we've seen the problem before, it can happen for different reasons, often the reason is unique. Here are some things you can try:

- Make sure you're using the latest version v2.3.3
- Open the JS console (Ctrl + Shift + J), are there any errors?
- View the page source, and look near the bottom. Is there some issue? You could send the source to us at ads_extension_magento@fb.com and we can take a look too.
- Clear the Magento Cache and Disable Compilation Mode and try again.
- Does the catalog have a non zero number of products?

If none of those work, consider enabling logging in Magento and emailing us your server PHP logs after attempting an install. This may help us debug the problem.

**Comment by FelipeMartinin** [comment] 2017-11-22 19:21
@dmitridr I'm with the same issue here. At the console I can see the follow error: 

![image](https://user-images.githubusercontent.com/5143508/33145818-00304c26-cfa9-11e7-8e55-279fe2adbcd5.png)


Any idea what it might be?  

Some points: 

- I'm using magento v1.9.2.4

- Cache cleaned and compilation mode disabled 

- I'm not with zero number of products


Thanks in advance.

**Comment by raulw** [comment] 2017-11-22 20:11
Same problem here... (exactly the errors above, posted by @FelipeMartinin )
Using: Magento 1.9.3.4 and Facebook for Magento tried with 2 versions, 2.3.3 and 2.3.4. 
Already tried: All the things above.

**Comment by dmitridr** [comment] 2017-11-30 20:13
Hello All,

Sorry to hear that you are having the same issue & thanks for trying all the suggestions.
Could you also confirm that the 'blank screen' you get is the one in this issue and not the one in #21 ?
You could also 'view source' and confirm if the problem is the same as in #21. In which case, we can move the discussion there.

If it is a separate problem, I am not sure what this could be. We would have to ask one or both of you to send us temporary login credentials to ads_extension_magento@fb.com so that we can login and investigate the problem (That's how we solved it in previous cases). We may also need permission to update the extension version on your site in order to test potential fixes.

**Comment by dmitridr** [comment] 2017-11-30 20:18
Also, as I said above, if you find any relevant exceptions in your PHP server logs or Magento exception logs, please email us those. We may be able to solve the problem using just those, if you find any.

**Comment by FelipeMartinin** [comment] 2017-12-03 17:50
Hello @dmitridr, thanks to reply. 

Right of the bat I saw that my issue is not the same of the issue  #21. 

As you suggested I just sent a email with my access for you guys investigate what's happening.

Best regards

**Comment by FelipeMartinin** [comment] 2017-12-08 19:06
@dmitridr I sent my access to  ads_extension_magento@fb.com  at the same day of my last message, and I didn't get a return til now.

**Comment by dmitridr** [comment] 2017-12-08 19:57
Hello @FelipeMartinin Thanks for your patience. I confirm that I received the access. I will look today and see if I can debug the problem, will update here with what I find.

**Comment by dmitridr** [comment] 2017-12-08 22:54
@FelipeMartinin , it seems that at least one of the issues is that your currency conversion rates are blank. When fetching product samples for your store, we attempt to convert to the currency of the default store, but the conversion rate is 1/0, which causes everything to crash.

Could you try to add currency conversion rates to your store via `System > Currency > Rates` ? I suspect it will fix the problem (unless there is another one). I will email you a screenshot.

**Comment by FelipeMartinin** [comment] 2017-12-10 21:48
@dmitridr Your suggestion works to me. Thanks a lot! 

In the end instead of specify a current rate, I let my local currency (BRL) as unique currency in magento. By default Magento load other currencies by default.

I this configuration in: `System > Configuration > Advanced > System [Currency]`

I hope this solution works to anyone else that's having this same problem.

Thanks again.

Best regards.

**Comment by dmitridr** [comment] 2017-12-11 20:27
Glad it helped!! 

@giftipedia Did the suggested fix work for you? We should have a mitigation in the next version which will show an error + helpful instructions rather than a blank screen for this specific problem.

**Comment by dmitridr** [comment] 2017-12-16 01:01
[v2.3.6](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.3.6) is out and will display an error screen instead of a blank screen if the currency issue is encountered.

@giftipedia @raulw encourage you to try this new version and/or check your currency rates to see if you have the same issue. Closing.

**Closed by dmitridr** 2017-12-16 01:01 UTC
Labels: bug

**Comment by ccalebb** [comment] 2018-02-21 21:07
<img width="1230" alt="screen shot 2018-02-21 at 2 06 07 pm" src="https://user-images.githubusercontent.com/33035550/36505357-774f4808-1710-11e8-8cfc-632d00a4b6df.png">

These are the errors I am receiving. Solutions mentioned above do not seem to be working.
