### ISSUE TITLE
For Magento 1.9.2.1 i don't see the get started button

### ISSUE THREAD

**Issue by Sambuca85** [facebookincubator/facebook-for-magento#51] opened 2018-04-10 15:39 UTC
Hi,
i've Magento 1.9.2.1 and i don't see the "Get Started" button. Can you solve this problem? Thanks.

**Comment by dmitridr** [comment] 2018-04-11 18:59
Hello, 

Can you confirm that you are using the latest version of the extension v2.4.1 and please take a look at #21 #42 and try to see if any of the suggestions in those issues fix the issue?

Usually this happens because your sample products could not be fetched correctly due to an exception.

**Comment by dmitridr** [comment] 2018-06-08 23:09
Closing as this is a duplicate of #42. #59.

**Closed by dmitridr** 2018-06-08 23:09 UTC
Labels: bug, duplicate
