### ISSUE TITLE
category not filled (productsets)

### ISSUE THREAD

**Issue by bvisje** [facebookincubator/facebook-for-magento#58] opened 2018-04-20 14:35 UTC
I want to create Product sets based on the category where the product is placed.
We are using version 2.4.1 on Magento 1.9.3.2

Also in facebook when going to all products the category is greyed out and not clickable. 

Is there something wrong on our part or is this function not integrated in the extension?

**Comment by dmitridr** [comment] 2018-04-20 21:47
Hi @bvisje ,

We export the Magento Category field into the `Product Type` field, you should be able to use the `Product Type` field to create a product set based on the names of your categories.

Some context : the `Category` field on Facebook is very strict and must follow the Google Taxonomy, in general the Magento category fields do not follow such a taxonomy, so we can't populate this field on FB, but what we've done is populate the `Product Type` field instead.

Hope that helps.

**Comment by bvisje** [comment] 2018-04-23 08:32
Dead @dmitridr ,

I already saw that but the problem is i can only select the bottom category. For example i want to select our category Men Clothing. I simply cant cause i only can selected bottom categories for example Men Clothing -> T-Shirts but i want to create a product set with the whole category Men Clothing. 

Do you know how to accomplish this with the current version of the extension?

**Comment by mengyingdu** [comment] 2018-07-05 17:15
I don't think we currently support this @bvisje . Unless you have some workaround @dmitridr ?

**Comment by dmitridr** [comment] 2018-07-17 21:52
Our extension imports the Magento category (which is not compatible with google product category in most cases), into the `product_type` field. You should be able to create product sets with this field @bvisje.

You can see in the docs for feed files:
https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog/

`product_type` is the custom category defined by you, in this case used by the extension. Hope that helps!

**Comment by dmitridr** [comment] 2018-07-17 21:55
@bvisje you should be able to add a rule that `Product Type` contains `Men Clothing` if the category is called `Men Clothing`. If you are encountering some kind of bug in our interfaces we can't help you unless you post a screenshot or a link to the interface so we can understand what the problem is.

@sulfurio Please open a separate issue if you believe the categories are wrong or being pulled from the wrong view (with some more details). I would double check this happens on the latest version.

The `google_product_category` field is pulled from the custom attribute `google_product_category` if it is present in your Magento store. If it is not present, it is empty.

**Comment by dmitridr** [comment] 2018-08-31 16:08
I will close this since this was mostly a question and I believe I have addressed the main concern, there has also not been a reply here in over a month. If there are still concerns, feel free to open another issue.

**Closed by dmitridr** 2018-08-31 16:08 UTC
Labels: question
