### ISSUE TITLE
Error admin (blank page) after install

### ISSUE THREAD

**Issue by arozmanroza** [facebookincubator/facebook-for-magento#84] opened 2018-08-25 21:42 UTC
After install in multiple domain Magento i got this error!

![magento_admin](https://user-images.githubusercontent.com/17758921/44622752-847ffb80-a8bf-11e8-9be9-59d29104f509.png)

in exception.log show error in

Facebook_AdsExtension_Block_ViewCategory
Facebook_AdsExtension_Block_AddToCart
...

but Page Source stops at

`div class="nav-bar" - menu start 
`

**Comment by dmitridr** [comment] 2018-08-27 15:10
Hi, what's the version of the plugin and the version of magento? 
If it's 2.6.0 can you try using 2.5.0 and see if you have the same result?

Versions are available [here](https://github.com/facebookincubator/facebook-for-magento/releases).

**Comment by arozmanroza** [comment] 2018-08-28 07:30
I have last version. 2.6.
In one other shop without multidomain shop, works fine.

**Comment by dmitridr** [comment] 2018-08-30 22:33
Could be related to several errors we received for 2.6. We will release 2.6.1 shortly, maybe it'll help.

**Comment by dmitridr** [comment] 2018-08-31 16:10
[v2.6.1](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.6.1) is out, could you try this version to see if you have the same issue? I also recommend trying [v2.5.0](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.5.0), it will help us narrow down the problem if it's caused by recent changes or what.

You could also try disabling compilation mode (if it's enabled), I've seen problems similar to yours caused by this.

**Comment by arozmanroza** [comment] 2018-09-02 17:10
It's better! Front web store is not destroy. Ist work, before 2.6.1 has white screen. Administration is the same! 
Page Source stops at
div class="nav-bar" - menu start

**Comment by dmitridr** [comment] 2018-09-21 14:56
Do you have logging enabled in Magento? Is there any log with exception you can share with us?
If the entire Admin does not work it looks like there is an exception somewhere, but we can't tell what the issue is without lots of help from you on this, unfortunately. 

My best guess is the extension is making incorrect assumptions about the multidomain store, and this results in an exception. But we need the actual exception to fix it.

Also could you share your Magento version?

**Comment by dmitridr** [comment] 2018-12-04 22:21
I'm marking this as duplicate with #21, if there are any updates please continue the discussion there. Hopefully we can update debug mode to be more robust and able to deal with these cases so that debugging can be done more effectively.

**Closed** 2018-12-04 22:22 UTC
Labels: bug, duplicate

**Comment by arozmanroza** [comment] 2019-03-07 19:55
Install 2.6.2 version and working fine! Thanks
