### ISSUE TITLE
Automatic Upload Issues

### ISSUE THREAD

**Issue by bedroomathletics** [facebookincubator/facebook-for-magento#12] opened 2017-10-10 10:42 UTC
Hi guys,

Automatic uploads are uploading just 141 products. I have to 'fetch now' with a manual uplaod to grab the full 585 products (despite not generating a new .tsv)

This is very odd. 

![capture](https://user-images.githubusercontent.com/32071663/31382563-06158522-adb0-11e7-807a-350a3acf6a06.PNG)
![capture2](https://user-images.githubusercontent.com/32071663/31382564-062f7658-adb0-11e7-9462-d69b314f822e.PNG)

**Comment by dmitridr** [comment] 2017-10-10 23:47
Hello Again, 

This appears to be the issue I mentioned in #3 ... for some reason the php process generating the feed file on your server is crashing when generating the feed, it crashes around the 141st product. We're not sure why, but it could be caused by a specific product. 

Do you have logging enabled or any access to the server PHP error logs? If there is an exception there during feed generation that you can send to us, maybe we can identify and fix it. 

In the meantime, I recommend disabling the daily upload schedule and periodically syncing with 'Fetch Now' if this problem persists.

Also, this is just a thought, but do you have Cron jobs enabled? That could be relevant to the cause.

**Comment by bedroomathletics** [comment] 2017-10-11 08:35
Hi there,

Apologies, totally forgot this was the issue in the other ticket.

Logs;
[18-Sep-2017 16:06:44 UTC] PHP Fatal error:  Call to a member function read() on a non-object in /home/SERVER/public_html/app/code/community/Facebook/AdsToolbox/controllers/ProductfeedController.php on line 42

Not sure if this helps? Nothing at the time of upload it appears though. 

Cron jobs are also enabled :)

**Comment by dmitridr** [comment] 2017-12-21 22:55
Hi again,

Thanks for taking the time to send us your log. Sorry for the long delay in getting back to you.

If you're still having this problem, I advise upgrading to our [latest version, v2.3.6](https://github.com/facebookincubator/facebook-for-magento/releases). We fixed a memory leak in #17  which was likely the cause of your feed generation crashing as well, especially if that was the only exception you saw in your log.

**Comment by dmitridr** [comment] 2018-03-23 01:50
I'm closing this since it's been a while since the last message, but I'm reasonably sure the memory leak fix would have fixed this issue.

**Closed by dmitridr** 2018-03-23 01:50 UTC
Labels: bug
