### ISSUE TITLE
Configured but saying "No facebook pixel is configured, please log in as a admin and then visit Facebook Ads Extension -> Get Started"

### ISSUE THREAD

**Issue by JoelSParker** [facebookincubator/facebook-for-magento#40] opened 2018-03-16 22:53 UTC
We went through the entire process and everything appears to be configured on the backend. However, the frontend is saying that "No facebook pixel is configured, please log in as a admin and then visit Facebook Ads Extension -> Get Started" in the console and is not outputting the pixel in the code.

**Comment by dmitridr** [comment] 2018-03-16 23:27
Hello,

Thanks for writing in. Could it be a Cache issue? Please try flushing the Cache if you have one.
Could you also confirm you have the latest version v2.4.0?

**Comment by JoelSParker** [comment] 2018-03-16 23:34
Yes, that was the first thing I tried.

**Comment by dmitridr** [comment] 2018-03-16 23:47
Hmm. So [this](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/design/frontend/base/default/template/facebook_ads_extension/head.phtml#L2) bit of code controls the message you saw. essentially it boils down to If the pixel ID can't be fetched from the DB, you'll see the message you saw. If it's not the cache, the other option is it wasn't properly set.

Could you check the table `core_config_data` in Magento, for the path `facebook_ads_toolbox/fbpixel/id` ? It should have the ID of the pixel. Also if you can share your store ID or store URL, I can check our own logging to see if we got a confirmation of the pixel being set or maybe there was an error when setting.

**Comment by JoelSParker** [comment] 2018-03-16 23:55
![image](https://user-images.githubusercontent.com/6782101/37549168-ef781094-2953-11e8-8610-1a0f0a8149b5.png)
This is what is the database for paths like "%facebook%".

the URL is https://joyfolie.com

**Comment by JoelSParker** [comment] 2018-03-20 13:36
I added the pixel ID manually to the database and now that is working. However, the products aren't syncing which I assume is a result of an issue somewhere. Do you have any ideas about that one?

**Comment by dmitridr** [comment] 2018-03-20 23:54
Nice way to fix it, I confirmed that it failed to set in our logs. Not sure why, if you have any log files there's likely to be an exception there related to Facebook which could be useful for us in order to fix the problem.

It seems like your products are uploading. I see them inside the catalog, which you can find in [catalog manager](https://www.facebook.com/products/catalogs/966659180175985/products). 

There's a common misconception that the products will appear on your page after the upload, but that will only happen if you have shops enabled under advanced settings in our latest version (v2.4.0)

**Comment by dmitridr** [comment] 2018-05-22 22:59
Closing since the issue seems rare and has a workaround. We won't try to debug further.

**Closed by dmitridr** 2018-05-22 22:59 UTC
Labels: bug, workaround
