### ISSUE TITLE
Import magento products in Shop

### ISSUE THREAD

**Issue by pako-g** [facebookincubator/facebook-for-magento#33] opened 2018-02-16 14:10 UTC
I did not understand if this magento plugin allows you to import products in shops or you have to do advertising.

Can I import the products without advertising?

**Comment by dmitridr** [comment] 2018-02-17 02:40
Hi. You can important the products and not run ads, yes. But unfortunately you can't auto-create shops... yet. though it is the next feature that we plan to add, I am thinking ~1 month for that. #26 has more details.

This extension does create a product feed which you may be able to reuse when creating a shop manually. #9 has some steps on how to do this, but it's very complicated.

**Comment by dmitridr** [comment] 2018-03-13 00:33
Closing this, as it's a duplicate of #26 , we should have shops support very soon. v2.4.0 will come out later today or tomorrow.

**Closed by dmitridr** 2018-03-13 00:33 UTC
Labels: duplicate, question
