### ISSUE TITLE
"Out Of Stock" products showing in Facebook Shop : Add option to hide them in shop only?

### ISSUE THREAD

**Issue by andymcp16** [facebookincubator/facebook-for-magento#70] opened 2018-06-13 13:48 UTC
Hi,
1. Any way to remove "Out Of Stock" products from the Facebook Shop?
These products do not display on the website when out of stock.
![out-of-stock-product](https://user-images.githubusercontent.com/39345136/41358723-e5b2d266-6f20-11e8-9257-63b703d5ace0.png)

2. Any way to change the default sorting of "All Products"
![deafult-sorting-all-products](https://user-images.githubusercontent.com/39345136/41358624-a89ae49a-6f20-11e8-8f31-91082ad85805.png)

thanks in advance,
Andrew

**Comment by andymcp16** [comment] 2018-06-14 08:08
Hi,
an option in the shop to hide out of stock products sounds perfect. Will they reappear again in the FB shop the next time they are in stock and the feed syncs?

Yes I have created multiple collections. It is just that the products ordered at the start of All Products appear on the Facebook homepage, some of which are out of stock and not top sellers.

If out of stock items could be hidden each time the feed is synced that would be amazing.

many thanks,
Andrew

**Comment by dmitridr** [comment] 2018-06-20 19:28
Hi Andrew,

Yes if we build it the right way that should be the behavior.
I'll see what we can do, it may take some time though, but i'll update here when there's progress.

**Comment by andymcp16** [comment] 2018-06-21 07:51
Thanks @dmitridr .

Sound great.

**Comment by leonardobussolo** [comment] 2018-06-25 19:28
I'm having the same issue here. In the feed catalog there are a lot of products out of stock that keeps appearing in the remarketing ads. The feed catalog shows the availability as "in stock" but in the Magento shop the product is "out of stock"

**Comment by dmitridr** [comment] 2018-06-25 20:12
@leonardobussolo That sounds like a bit of a separate issue from what is discussed here, though the feature requested here might solve it. Out of stock products may appear in ad preview, but should not appear in ads shown to customers. 

If you have a screenshot of your ad in news feed (not as a result of preview!) showing an out of stock product, please post that along with the user ID, ad ID, and approximate time it was viewed. I can file a bug report on the Dynamic Ads team, this should not happen. (Feel free to email this to ads_extension@fb.com if you don't want to post it here).

**Comment by leonardobussolo** [comment] 2018-06-25 20:28
@dmitridr 
I have one screenshot from it happening in the news feed:
![screenshot-remarketing-fb](https://user-images.githubusercontent.com/32716130/41873646-fc8b8882-789b-11e8-9114-73a411817b1f.jpg)

And this is the screenshot of some sold out products that in the feed catalog appears as "in stock":

![captura de tela 2018-06-25 as 17 25 14](https://user-images.githubusercontent.com/32716130/41873918-caf6ccb8-789c-11e8-844e-8c5aad671e96.png)
Catalog ID: 195133271092736
Products links:
https://anurbanshop.com.br/marcador-mtn-marker-30.html
https://anurbanshop.com.br/camiseta-dgk-seduce-branca.html
https://anurbanshop.com.br/livro-upper-playground-grotesk-a-decade-of-swiss-design-lost-in-brooklyn.html

**Comment by dmitridr** [comment] 2018-06-25 20:32
Ah if the problem is the products are incorrectly marked as "in stock" then it's a different issue. In fact the feature I am building to solve the original problem in this thread will not help your situation.

#6 is the long standing issue causing your problem, let's discuss further there.

**Comment by leonardobussolo** [comment] 2018-06-25 20:33
@dmitridr Ok, thanks!

**Comment by coldnose** [comment] 2018-11-16 01:05
Thanks for creating the FB extension for Magento. However, including out-of-stock items from Magento for display on FB, let alone marketing them is not useful. The extension really has no value until the functionality of excluding out-of-stock products is added. I hope this is addresed soon.

**Comment by dmitridr** [comment] 2018-12-03 23:21
Thanks for the feedback. An advanced option to not sync out of stock items is certainly possible, and not very difficult to implement. However the underlying issue #6 is more significant, as items are incorrectly labeled, we will try to solve that first then get to this.

**Comment by dmitridr** [comment] 2018-12-07 22:21
Hi all,

We've implemented an advanced option in [v2.6.2](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.6.2) which will not sync out of stock items with FB when checked. Please try selecting the option and doing a `Fetch Now` to refresh the feed file. If it doesn't work, open a new issue on us and reference this one! 

Keep in mind, this will not only hide the products from the shop, but won't make them available in the catalog for advertising as well (though I don't know why you'd want to advertise out of stock products, perhaps somebody out there does).

**Closed by dmitridr** 2018-12-07 22:21 UTC
Labels: feature-request, follow up for next release, shop-feature-request

**Comment by newsjunk** [comment] 2019-07-11 11:07
@dmitridr we just updated to the latest version (may 2019) but I cannot find this screen you mentioned. Where should I be able to find it?
