### ISSUE TITLE
Bad encoding in the generated file for feeding magento products in facebook

### ISSUE THREAD

**Issue by hristopeev** [facebookincubator/facebook-for-magento#13] opened 2017-10-11 14:16 UTC
Hello,

We have Magento 1.9.3.4 store and we are using your extension for feeding our Facebook Business Product Catalog and run ads based on them.

Currently our store is in Bulgarian language and respectively all product titles, descriptions and attributes are in Bulgarian.

When we try the automatic fetch from the following screen:
[Fetch Screen](https://www.dropbox.com/s/m3xmjx1z7mmx8jk/fetch_products_screen.png?dl=0)

The result is 99.3% of our products are rejected due to errors:
[Upload session status - 99.3% rejected](https://www.dropbox.com/s/pgvbj2o35ewbzoz/upload_session_status.jpg?dl=0) 

And here is the product review:
[Products Review](https://www.dropbox.com/s/zlc048jpdn816zw/upload_session_preview.jpg?dl=0)

So it seems that the file is generated in encoding not supported by the FB Business fetcher. 

If we download the file locally and open and save it as UTF-8 and then upload in FB Business it is interpreted successfully and all products are processed correctly.

The site is [topoutfit.com](https://topoutfit.com) and the file generated by your module is [here](topoutfit.com/media/facebook_adstoolbox_product_feed.tsv).

Is there a way to force the module to generate the content in UTF-8 encoding?

If you need any additional information for identifying the problem I am ready to assist.

Thanks!

**Comment by dmitridr** [comment] 2017-10-11 20:24
Hello, 

Thanks for writing in with detailed information. 
I checked [your catalog](https://www.facebook.com/products/catalogs/2031645360387842/feeds/137740220173162/overview) inside our catalog manager tool and wasn't able to detect any problem. This page should also be visible to you as the owner of the catalog.

Since it seems there is no problem there, I'm guessing that the problem is with a different catalog which you set up with `FB Business fetcher`, which is not familiar to me. If that is the case you should ensure that the settings of the product feed you created are set to Encoding : UTF-8. If you tell us the ID of the feed which has the problem, we can do that for you. 

An alternative solution is to use the catalog I linked and attach it to your business using the settings page, which should also work. Let us know if that helps.

**Comment by bedroomathletics** [comment] 2017-10-12 09:26
That feed you must have checked after my manual upload - If you look at that link now, you will see that only 151 items have been uploaded from the scheduled upload from the early hours this morning...

appreciate the support :)

**Comment by hristopeev** [comment] 2017-10-12 11:41
First of all thanks for the response!

Yes, exactly. If we download the file, open and save it as UTF-8 and then upload it manually everything is OK. But the automatic daily upload does not work.

Let me know if you need more info for figuring our the problem.

**Comment by dmitridr** [comment] 2017-10-12 23:27
Hello @hristopeev 

We still don't see the problem. Could you try this link:

https://www.facebook.com/products/catalogs/2031645360387842/feeds/137740220173162/overview

It shows that the products are uploading just fine on a daily basis. According to our logs, this was the catalog created for topoutfit.com when you set up the extension.

**Comment by dmitridr** [comment] 2017-11-30 20:06
I will close this for now, as it seems the products are uploading fine in the above link. Please feel free to open a new issue and reference this one if the problem persists.

**Closed by dmitridr** 2017-11-30 20:06 UTC
